// Generates src/parsers/srum/names.ts from his Srum library's source
// (https://github.com/EricZimmerman/Srum, SrumData/Srum.cs, MIT): the
// InterfaceType enum and GetSidTypeFromSidString's mapping.
//
//   node scripts/gen-srum.mjs path/to/Srum/SrumData/Srum.cs
import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2];
if (!src) throw new Error('usage: node scripts/gen-srum.mjs <Srum.cs>');
const cs = readFileSync(src, 'utf8');

const block = (start) => {
  const i = cs.indexOf(start);
  if (i < 0) throw new Error(`not found: ${start}`);
  return cs.slice(i, cs.indexOf('\n}', i));
};

// enum InterfaceType { IF_TYPE_X = 133, ... }
const interfaces = {};
for (const m of block('public enum InterfaceType').matchAll(/(IF_TYPE_\w+)\s*=\s*(\d+)/g)) interfaces[m[2]] ??= m[1];

// switch (sid) { case "S-1-0-0": sidType = SidTypeEnum.Null; ... }
const fn = block('public static SidTypeEnum GetSidTypeFromSidString');
const exact = {};
for (const m of fn.matchAll(/case\s+"([^"]+)":\s*sidType\s*=\s*SidTypeEnum\.(\w+);/g)) exact[m[1]] ??= m[2];
const prefixes = [...fn.matchAll(/if\s*\(sid\.StartsWith\("([^"]+)"\)\)\s*\{\s*sidType\s*=\s*SidTypeEnum\.(\w+);/g)].map((m) => [m[1], m[2]]);
const suffixes = [
  ...fn.matchAll(/if\s*\(sid\.StartsWith\("([^"]+)"\)\s*&&\s*sid\.EndsWith\("([^"]+)"\)\)\s*\{\s*sidType\s*=\s*SidTypeEnum\.(\w+);/g),
].map((m) => [m[1], m[2], m[3]]);

const out = `// Auto-generated by scripts/gen-srum.mjs from his Srum library's
// SrumData/Srum.cs (https://github.com/EricZimmerman/Srum). Do not edit by hand.

/** InterfaceType by value. */
export const INTERFACE_TYPES: Record<number, string> = ${JSON.stringify(interfaces)};

/** GetSidTypeFromSidString: exact SIDs first. */
export const SID_TYPES: Record<string, string> = ${JSON.stringify(exact)};

/** Then, for an unknown SID, these prefixes... */
export const SID_PREFIXES: Array<[string, string]> = ${JSON.stringify(prefixes)};

/** ...and these prefix-and-suffix pairs, each overriding the last. */
export const SID_SUFFIXES: Array<[string, string, string]> = ${JSON.stringify(suffixes)};
`;
writeFileSync(new URL('../src/parsers/srum/names.ts', import.meta.url), out);
console.log(`${Object.keys(interfaces).length} interface types, ${Object.keys(exact).length} SIDs, ${prefixes.length} prefixes, ${suffixes.length} suffixes`);
