// Generates src/parsers/sqlite/maps.ts from SQLECmd's map files
// (https://github.com/EricZimmerman/SQLECmd, SQLMap/Maps/*.smap, MIT).
//
//   node scripts/gen-sqlmaps.mjs path/to/SQLECmd/SQLMap/Maps
//
// As his SqlMap.LoadMaps does: every .smap under the folder, in path order,
// kept only when his MapFileMapValidator would pass it, and a map whose Id
// (upper-cased) was already loaded is skipped. Scalars are read as strings, as
// YamlDotNet reads them into his string properties: IdentifyValue "1.0" stays
// "1.0".
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { parse } from 'yaml';

const root = process.argv[2];
if (!root) throw new Error('usage: node scripts/gen-sqlmaps.mjs <SQLMap/Maps>');

const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : e.name.toUpperCase().endsWith('.SMAP') ? [join(dir, e.name)] : [],
  );

const filled = (v) => typeof v === 'string' && v.trim() !== '';
const maps = [];
const ids = new Set();
const rejected = [];
for (const file of walk(root).sort((a, b) => a.localeCompare(b, 'en'))) {
  const name = relative(root, file);
  let m;
  try {
    m = parse(readFileSync(file, 'utf8'), { schema: 'failsafe' });
  } catch (e) {
    rejected.push(`${name}: ${e.message.split('\n')[0]}`);
    continue;
  }
  const queries = Array.isArray(m?.Queries) ? m.Queries : null;
  const valid =
    m &&
    typeof m.Description === 'string' &&
    typeof m.CSVPrefix === 'string' &&
    ['Author', 'Email', 'Id', 'Version', 'FileName', 'IdentifyQuery', 'IdentifyValue'].every((k) => filled(m[k])) &&
    (queries === null || queries.length > 0) &&
    (queries ?? []).every(
      (q) =>
        q &&
        ['Name', 'Query', 'BaseFileName'].every((k) => filled(q[k])) &&
        (q.BlobColumns ?? []).every((b) => filled(b?.BlobColumn)),
    );
  if (!valid) {
    rejected.push(`${name}: fails his validator`);
    continue;
  }
  const id = m.Id.toUpperCase();
  if (ids.has(id)) {
    rejected.push(`${name}: duplicate Id ${m.Id}`);
    continue;
  }
  ids.add(id);
  maps.push({
    id: m.Id,
    description: m.Description,
    csvPrefix: m.CSVPrefix,
    fileName: m.FileName,
    identifyQuery: m.IdentifyQuery,
    identifyValue: m.IdentifyValue,
    queries: (queries ?? []).map((q) => ({
      name: q.Name,
      query: q.Query,
      baseFileName: q.BaseFileName,
      blobColumns: (q.BlobColumns ?? []).map((b) => b.BlobColumn),
    })),
  });
}

const out = `// Auto-generated by scripts/gen-sqlmaps.mjs from SQLECmd's SQLMap/Maps
// (https://github.com/EricZimmerman/SQLECmd). ${maps.length} maps. Do not edit by hand.
export interface SqlQuery {
  name: string;
  query: string;
  baseFileName: string;
  blobColumns: string[];
}
export interface SqlMap {
  id: string;
  description: string;
  csvPrefix: string;
  fileName: string;
  identifyQuery: string;
  identifyValue: string;
  queries: SqlQuery[];
}
export const SQL_MAPS: SqlMap[] = ${JSON.stringify(maps, null, 1)};
`;
writeFileSync(new URL('../src/parsers/sqlite/maps.ts', import.meta.url), out);
console.log(`${maps.length} maps, ${maps.reduce((n, m) => n + m.queries.length, 0)} queries`);
for (const r of rejected) console.log(`skipped ${r}`);
